import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * 多书籍侧边栏配置
 * 每本书一个独立的 sidebar
 */
const sidebars: SidebarsConfig = {
  // 《玩转 n8n：小白也能学会的自动化》
  basicsSidebar: [
    {
      type: "category",
      label: "📘 玩转 n8n",
      link: {
        type: "doc",
        id: "n8n-basics/intro",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "n8n-basics",
        },
      ],
    },
  ],

  // 未来可扩展：外贸书籍
  // tradeSidebar: [
  //   {
  //     type: "autogenerated",
  //     dirName: "n8n-trade",
  //   },
  // ],
};

export default sidebars;
